apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: couchdb-operator
  template:
    metadata:
      labels:
        name: couchdb-operator
    spec:
      serviceAccountName: couchdb-operator
      containers:
        - name: couchdb-operator
          # Replace this with the built image name
          image: yobitel/couchdb-operator:3.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "couchdb-operator"
